### ISSUE TITLE
Windows 10 should be parsed as osFamily=Windows osMajor=10

### ISSUE THREAD

**Issue by Krinkle** [ua-parser/uap-core#67]
Right now it's parsed as its own family, no longer part of "Windows".

**Comment by shashank-** [comment]
This is how every version of Windows is being translated, likely because Windows switch (back) to number started with 7 (XP, Vista, etc...).

Seen the following be translated for ourselves:
Windows RT   
Windows Phone    
Windows 7    
Windows 10   
Windows Vista    
Windows 8    
Windows 8.1  
Windows XP   
Windows
Windows 2000     
Windows NT 4.0   
Windows RT 8.1   
Windows 95   
Windows 98   
Windows ME   
Windows Mobile
